package pojo;
// Generated Jun 19, 2018 11:31:05 AM by Hibernate Tools 4.3.1



/**
 * Attachmantbyofficer generated by hbm2java
 */
public class Attachmantbyofficer  implements java.io.Serializable {


     private Integer idAttachmantByOfficer;
     private Mailinfo mailinfo;
     private Proces proces;
     private User user;
     private String attachmantByOfficerTitle;
     private String attachmantByOfficerPath;
     private Integer attachmantByOfficerNumber;

    public Attachmantbyofficer() {
    }

	
    public Attachmantbyofficer(Mailinfo mailinfo, Proces proces, User user) {
        this.mailinfo = mailinfo;
        this.proces = proces;
        this.user = user;
    }
    public Attachmantbyofficer(Mailinfo mailinfo, Proces proces, User user, String attachmantByOfficerTitle, String attachmantByOfficerPath, Integer attachmantByOfficerNumber) {
       this.mailinfo = mailinfo;
       this.proces = proces;
       this.user = user;
       this.attachmantByOfficerTitle = attachmantByOfficerTitle;
       this.attachmantByOfficerPath = attachmantByOfficerPath;
       this.attachmantByOfficerNumber = attachmantByOfficerNumber;
    }
   
    public Integer getIdAttachmantByOfficer() {
        return this.idAttachmantByOfficer;
    }
    
    public void setIdAttachmantByOfficer(Integer idAttachmantByOfficer) {
        this.idAttachmantByOfficer = idAttachmantByOfficer;
    }
    public Mailinfo getMailinfo() {
        return this.mailinfo;
    }
    
    public void setMailinfo(Mailinfo mailinfo) {
        this.mailinfo = mailinfo;
    }
    public Proces getProces() {
        return this.proces;
    }
    
    public void setProces(Proces proces) {
        this.proces = proces;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getAttachmantByOfficerTitle() {
        return this.attachmantByOfficerTitle;
    }
    
    public void setAttachmantByOfficerTitle(String attachmantByOfficerTitle) {
        this.attachmantByOfficerTitle = attachmantByOfficerTitle;
    }
    public String getAttachmantByOfficerPath() {
        return this.attachmantByOfficerPath;
    }
    
    public void setAttachmantByOfficerPath(String attachmantByOfficerPath) {
        this.attachmantByOfficerPath = attachmantByOfficerPath;
    }
    public Integer getAttachmantByOfficerNumber() {
        return this.attachmantByOfficerNumber;
    }
    
    public void setAttachmantByOfficerNumber(Integer attachmantByOfficerNumber) {
        this.attachmantByOfficerNumber = attachmantByOfficerNumber;
    }




}


