package pojo;
// Generated Jun 22, 2018 9:23:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private Integer idDepartment;
     private String departmentName;
     private Integer departmentStatus;
     private Set<Userhasdepartment> userhasdepartments = new HashSet<Userhasdepartment>(0);
     private Set<Proces> proceses = new HashSet<Proces>(0);

    public Department() {
    }

    public Department(String departmentName, Integer departmentStatus, Set<Userhasdepartment> userhasdepartments, Set<Proces> proceses) {
       this.departmentName = departmentName;
       this.departmentStatus = departmentStatus;
       this.userhasdepartments = userhasdepartments;
       this.proceses = proceses;
    }
   
    public Integer getIdDepartment() {
        return this.idDepartment;
    }
    
    public void setIdDepartment(Integer idDepartment) {
        this.idDepartment = idDepartment;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public Integer getDepartmentStatus() {
        return this.departmentStatus;
    }
    
    public void setDepartmentStatus(Integer departmentStatus) {
        this.departmentStatus = departmentStatus;
    }
    public Set<Userhasdepartment> getUserhasdepartments() {
        return this.userhasdepartments;
    }
    
    public void setUserhasdepartments(Set<Userhasdepartment> userhasdepartments) {
        this.userhasdepartments = userhasdepartments;
    }
    public Set<Proces> getProceses() {
        return this.proceses;
    }
    
    public void setProceses(Set<Proces> proceses) {
        this.proceses = proceses;
    }




}


