package pojo;
// Generated Jun 22, 2018 9:23:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docket generated by hbm2java
 */
public class Docket  implements java.io.Serializable {


     private Integer idDocket;
     private Rack rack;
     private String docketName;
     private Integer docketStatus;
     private Set<File> files = new HashSet<File>(0);

    public Docket() {
    }

	
    public Docket(Rack rack) {
        this.rack = rack;
    }
    public Docket(Rack rack, String docketName, Integer docketStatus, Set<File> files) {
       this.rack = rack;
       this.docketName = docketName;
       this.docketStatus = docketStatus;
       this.files = files;
    }
   
    public Integer getIdDocket() {
        return this.idDocket;
    }
    
    public void setIdDocket(Integer idDocket) {
        this.idDocket = idDocket;
    }
    public Rack getRack() {
        return this.rack;
    }
    
    public void setRack(Rack rack) {
        this.rack = rack;
    }
    public String getDocketName() {
        return this.docketName;
    }
    
    public void setDocketName(String docketName) {
        this.docketName = docketName;
    }
    public Integer getDocketStatus() {
        return this.docketStatus;
    }
    
    public void setDocketStatus(Integer docketStatus) {
        this.docketStatus = docketStatus;
    }
    public Set<File> getFiles() {
        return this.files;
    }
    
    public void setFiles(Set<File> files) {
        this.files = files;
    }




}


