package pojo;
// Generated Jul 2, 2018 1:15:52 PM by Hibernate Tools 4.3.1



/**
 * File generated by hbm2java
 */
public class File  implements java.io.Serializable {


     private Integer idFile;
     private Docket docket;
     private String fileNo;
     private String fileName;
     private Integer fileStatus;

    public File() {
    }

	
    public File(Docket docket) {
        this.docket = docket;
    }
    public File(Docket docket, String fileNo, String fileName, Integer fileStatus) {
       this.docket = docket;
       this.fileNo = fileNo;
       this.fileName = fileName;
       this.fileStatus = fileStatus;
    }
   
    public Integer getIdFile() {
        return this.idFile;
    }
    
    public void setIdFile(Integer idFile) {
        this.idFile = idFile;
    }
    public Docket getDocket() {
        return this.docket;
    }
    
    public void setDocket(Docket docket) {
        this.docket = docket;
    }
    public String getFileNo() {
        return this.fileNo;
    }
    
    public void setFileNo(String fileNo) {
        this.fileNo = fileNo;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Integer getFileStatus() {
        return this.fileStatus;
    }
    
    public void setFileStatus(Integer fileStatus) {
        this.fileStatus = fileStatus;
    }




}


