package pojo;
// Generated Jul 2, 2018 1:15:52 PM by Hibernate Tools 4.3.1



/**
 * Privilege generated by hbm2java
 */
public class Privilege  implements java.io.Serializable {


     private Integer idPrivilege;
     private Usercatagory usercatagory;
     private String privilegeName;
     private String privilegePath;
     private Integer privilegeOder;
     private Integer privilegeStatus;

    public Privilege() {
    }

	
    public Privilege(Usercatagory usercatagory) {
        this.usercatagory = usercatagory;
    }
    public Privilege(Usercatagory usercatagory, String privilegeName, String privilegePath, Integer privilegeOder, Integer privilegeStatus) {
       this.usercatagory = usercatagory;
       this.privilegeName = privilegeName;
       this.privilegePath = privilegePath;
       this.privilegeOder = privilegeOder;
       this.privilegeStatus = privilegeStatus;
    }
   
    public Integer getIdPrivilege() {
        return this.idPrivilege;
    }
    
    public void setIdPrivilege(Integer idPrivilege) {
        this.idPrivilege = idPrivilege;
    }
    public Usercatagory getUsercatagory() {
        return this.usercatagory;
    }
    
    public void setUsercatagory(Usercatagory usercatagory) {
        this.usercatagory = usercatagory;
    }
    public String getPrivilegeName() {
        return this.privilegeName;
    }
    
    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName;
    }
    public String getPrivilegePath() {
        return this.privilegePath;
    }
    
    public void setPrivilegePath(String privilegePath) {
        this.privilegePath = privilegePath;
    }
    public Integer getPrivilegeOder() {
        return this.privilegeOder;
    }
    
    public void setPrivilegeOder(Integer privilegeOder) {
        this.privilegeOder = privilegeOder;
    }
    public Integer getPrivilegeStatus() {
        return this.privilegeStatus;
    }
    
    public void setPrivilegeStatus(Integer privilegeStatus) {
        this.privilegeStatus = privilegeStatus;
    }




}


