package pojo;
// Generated Jul 10, 2018 4:31:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proces generated by hbm2java
 */
public class Proces  implements java.io.Serializable {


     private Integer idProces;
     private Department department;
     private Mailinfo mailinfo;
     private Mailstatus mailstatus;
     private User userByUserFrom;
     private User userByUserTo;
     private Integer procesOder;
     private String procesComent;
     private Integer procesStatus;
     private Set<Attachmantbyofficer> attachmantbyofficers = new HashSet<Attachmantbyofficer>(0);

    public Proces() {
    }

	
    public Proces(Department department, Mailinfo mailinfo, Mailstatus mailstatus, User userByUserFrom, User userByUserTo) {
        this.department = department;
        this.mailinfo = mailinfo;
        this.mailstatus = mailstatus;
        this.userByUserFrom = userByUserFrom;
        this.userByUserTo = userByUserTo;
    }
    public Proces(Department department, Mailinfo mailinfo, Mailstatus mailstatus, User userByUserFrom, User userByUserTo, Integer procesOder, String procesComent, Integer procesStatus, Set<Attachmantbyofficer> attachmantbyofficers) {
       this.department = department;
       this.mailinfo = mailinfo;
       this.mailstatus = mailstatus;
       this.userByUserFrom = userByUserFrom;
       this.userByUserTo = userByUserTo;
       this.procesOder = procesOder;
       this.procesComent = procesComent;
       this.procesStatus = procesStatus;
       this.attachmantbyofficers = attachmantbyofficers;
    }
   
    public Integer getIdProces() {
        return this.idProces;
    }
    
    public void setIdProces(Integer idProces) {
        this.idProces = idProces;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Mailinfo getMailinfo() {
        return this.mailinfo;
    }
    
    public void setMailinfo(Mailinfo mailinfo) {
        this.mailinfo = mailinfo;
    }
    public Mailstatus getMailstatus() {
        return this.mailstatus;
    }
    
    public void setMailstatus(Mailstatus mailstatus) {
        this.mailstatus = mailstatus;
    }
    public User getUserByUserFrom() {
        return this.userByUserFrom;
    }
    
    public void setUserByUserFrom(User userByUserFrom) {
        this.userByUserFrom = userByUserFrom;
    }
    public User getUserByUserTo() {
        return this.userByUserTo;
    }
    
    public void setUserByUserTo(User userByUserTo) {
        this.userByUserTo = userByUserTo;
    }
    public Integer getProcesOder() {
        return this.procesOder;
    }
    
    public void setProcesOder(Integer procesOder) {
        this.procesOder = procesOder;
    }
    public String getProcesComent() {
        return this.procesComent;
    }
    
    public void setProcesComent(String procesComent) {
        this.procesComent = procesComent;
    }
    public Integer getProcesStatus() {
        return this.procesStatus;
    }
    
    public void setProcesStatus(Integer procesStatus) {
        this.procesStatus = procesStatus;
    }
    public Set<Attachmantbyofficer> getAttachmantbyofficers() {
        return this.attachmantbyofficers;
    }
    
    public void setAttachmantbyofficers(Set<Attachmantbyofficer> attachmantbyofficers) {
        this.attachmantbyofficers = attachmantbyofficers;
    }




}


