package pojo;
// Generated Jul 10, 2018 4:31:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rack generated by hbm2java
 */
public class Rack  implements java.io.Serializable {


     private Integer idRack;
     private Cupboard cupboard;
     private String rackNo;
     private Integer rackStatus;
     private Set<Docket> dockets = new HashSet<Docket>(0);

    public Rack() {
    }

	
    public Rack(Cupboard cupboard) {
        this.cupboard = cupboard;
    }
    public Rack(Cupboard cupboard, String rackNo, Integer rackStatus, Set<Docket> dockets) {
       this.cupboard = cupboard;
       this.rackNo = rackNo;
       this.rackStatus = rackStatus;
       this.dockets = dockets;
    }
   
    public Integer getIdRack() {
        return this.idRack;
    }
    
    public void setIdRack(Integer idRack) {
        this.idRack = idRack;
    }
    public Cupboard getCupboard() {
        return this.cupboard;
    }
    
    public void setCupboard(Cupboard cupboard) {
        this.cupboard = cupboard;
    }
    public String getRackNo() {
        return this.rackNo;
    }
    
    public void setRackNo(String rackNo) {
        this.rackNo = rackNo;
    }
    public Integer getRackStatus() {
        return this.rackStatus;
    }
    
    public void setRackStatus(Integer rackStatus) {
        this.rackStatus = rackStatus;
    }
    public Set<Docket> getDockets() {
        return this.dockets;
    }
    
    public void setDockets(Set<Docket> dockets) {
        this.dockets = dockets;
    }




}


