package pojo;
// Generated Jun 19, 2018 11:31:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usercatagory generated by hbm2java
 */
public class Usercatagory  implements java.io.Serializable {


     private Integer idUserCatagory;
     private String userCatagoryName;
     private Integer userCatagoryStatus;
     private Set<User> users = new HashSet<User>(0);
     private Set<Privilege> privileges = new HashSet<Privilege>(0);

    public Usercatagory() {
    }

    public Usercatagory(String userCatagoryName, Integer userCatagoryStatus, Set<User> users, Set<Privilege> privileges) {
       this.userCatagoryName = userCatagoryName;
       this.userCatagoryStatus = userCatagoryStatus;
       this.users = users;
       this.privileges = privileges;
    }
   
    public Integer getIdUserCatagory() {
        return this.idUserCatagory;
    }
    
    public void setIdUserCatagory(Integer idUserCatagory) {
        this.idUserCatagory = idUserCatagory;
    }
    public String getUserCatagoryName() {
        return this.userCatagoryName;
    }
    
    public void setUserCatagoryName(String userCatagoryName) {
        this.userCatagoryName = userCatagoryName;
    }
    public Integer getUserCatagoryStatus() {
        return this.userCatagoryStatus;
    }
    
    public void setUserCatagoryStatus(Integer userCatagoryStatus) {
        this.userCatagoryStatus = userCatagoryStatus;
    }
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }
    public Set<Privilege> getPrivileges() {
        return this.privileges;
    }
    
    public void setPrivileges(Set<Privilege> privileges) {
        this.privileges = privileges;
    }




}


